'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    'NOTE: This file is auto-generated; do not modify it directly.  To make changes,
    ' or if you encounter build errors in this file, go to the Project Designer
    ' (go to Project Properties or double-click the My Project node in
    ' Solution Explorer), and make changes on the Application tab.
    '
    Partial Friend Class MyApplication
        
        <Global.System.Diagnostics.DebuggerStepThroughAttribute()>  _
        Public Sub New()
            MyBase.New(Global.Microsoft.VisualBasic.ApplicationServices.AuthenticationMode.Windows)
            Me.IsSingleInstance = false
            Me.EnableVisualStyles = true
            Me.SaveMySettingsOnExit = true
            Me.ShutDownStyle = Global.Microsoft.VisualBasic.ApplicationServices.ShutdownMode.AfterMainFormCloses
        End Sub
        
        <Global.System.Diagnostics.DebuggerStepThroughAttribute()>  _
        Protected Overrides Sub OnCreateMainForm()
            Me.MainForm = Global.isnotify.Form1
        End Sub

        Private Sub MyApplication_Startup(ByVal sender As Object, ByVal e As Microsoft.VisualBasic.ApplicationServices.StartupEventArgs) Handles Me.Startup
            Dim str() As String = Environment.GetCommandLineArgs
            If str.Count > 1 Then
                If str(1) = "0" Then
                    Form1.PictureBox1.Image = My.Resources.ud
                    Form1.Label1.Text = "USB bağlantısı kesildi"
                    Form1.Label1.ForeColor = Color.Red
                ElseIf str(1) = "1" Then
                    Form1.PictureBox1.Image = My.Resources.uc
                    Form1.Label1.Text = "USB bağlantısı kuruldu"
                    Form1.Label1.ForeColor = Color.Yellow
                ElseIf str(1) = "2" Then
                    Form1.PictureBox1.Image = My.Resources.bd
                    Form1.Label1.Text = "Bluetooth bağlantısı kesildi"
                    Form1.Label1.ForeColor = Color.Red
                ElseIf str(1) = "3" Then
                    Form1.PictureBox1.Image = My.Resources.bc
                    Form1.Label1.Text = "Bluetooth bağlantısı kuruldu"
                    Form1.Label1.ForeColor = Color.Yellow
                ElseIf str(1) = "4" Then
                    Form1.PictureBox1.Image = My.Resources.dc
                    Form1.Label1.Text = "Kapı kapatıldı"
                    Form1.Label1.ForeColor = Color.Yellow
                ElseIf str(1) = "5" Then
                    Form1.PictureBox1.Image = My.Resources._do
                    Form1.Label1.Text = "Kapı açıldı"
                    Form1.Label1.ForeColor = Color.Yellow
                Else
                    e.Cancel = True
                    End
                End If
                Form1.PictureBox2.BackColor = Form1.Label1.ForeColor
                Form1.PictureBox3.BackColor = Form1.Label1.ForeColor
                Form1.PictureBox4.BackColor = Form1.Label1.ForeColor
                Form1.PictureBox5.BackColor = Form1.Label1.ForeColor
            Else
                e.Cancel = True
                End
            End If
        End Sub
    End Class
End Namespace
